apiVersion: config.auditlog-forwarder.gardener.cloud/v1alpha1
kind: AuditlogForwarder

log:
  level: info
  format: json

server:
  port: 10443
  metricsPort: 8080
  address: ""

  tls:
    certFile: "/etc/certs/tls.crt"
    keyFile: "/etc/certs/tls.key"
    # clientCAFile: "/etc/certs/client-ca.crt"

outputs:
- http:
    url: https://example.com/v1/logs
    # compression: gzip
    tls:
      caFile: /etc/ssl/certs/ca-certificates.crt
      certFile: /etc/certs/client-cert.pem # optional - used for mutual TLS
      keyFile: /etc/certs/client-key.pem # optional - used for mutual TLS

injectAnnotations:
  shoot.gardener.cloud/id: id
  shoot.gardener.cloud/name: foo
  shoot.gardener.cloud/namespace: garden-example
