---
apiVersion: v1
kind: Service
metadata:
  name: auditlog-forwarder
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: auditlog-forwarder
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: auditlog-forwarder
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
  - port: 443
    name: https
    protocol: TCP
    targetPort: {{ .Values.config.server.port }}
    nodePort: 30021
  - port: 8080
    name: metrics
    protocol: TCP
    targetPort: {{ .Values.config.server.metricsPort }}
    nodePort: 30022
