tls:
  crt: |
    -----BEGIN CERTIFICATE-----
    MIID...
    -----END CERTIFICATE-----
  key: |
    -----BEGIN PRIVATE KEY-----
    MIIE...
    -----END PRIVATE KEY-----
  clientCA: |
    -----BEGIN CERTIFICATE-----
    MIID...
    -----END CERTIFICATE-----

output:
  clientCrt: |
    -----BEGIN CERTIFICATE-----
    MIID...
    -----END CERTIFICATE-----
  clientKey: |
    -----BEGIN PRIVATE KEY-----
    MIIE...
    -----END PRIVATE KEY-----

image:
  repository: local-skaffold/auditlog-forwarder
  tag: latest

config:
  log:
    level: info
    format: json

  server:
    port: 10443
    metricsPort: 8080
    address: ""
